### ISSUE TITLE
Add shortcut to switch between VFO / Memory Mode

### ISSUE THREAD

**Issue by marrold** [marrold/HG-UV98#2]
Currently to switch between VFO and Memory Mode you have to navigate through the menus.

It would be ideal if you could either use on of the side function keys, or a long press on the front keypad to switch between VFO and Memory Mode.

**Comment by ornotermes** [comment]
Try holding the red button to cycle through VFO / MEM freq / MEM number / MEM name.

**Comment by marrold** [comment]
Yup, that's what I was missing. Thanks
