### ISSUE TITLE
Groups.io and github dead?

### ISSUE THREAD

**Issue by musiclandUSA** [marrold/HG-UV98#29]
I just bought one of these radios and was excited in some developments but it seems like all the activity died months ago.  No one appears to be manning the group and approving messages so its dead as well.

**Comment by PorterRyan** [comment]
I hope not, I've got mine in the mail. This radio is the next best option for APRS with APRSDroid considering the lack of availability for MobilLinkDs.

**Comment by musiclandUSA** [comment]
There's a recent topic about winlink but my submitted post from weeks ago still hasn't shown up, something is weird over there

**Comment by ornotermes** [comment]
@musiclandUSA Have you tried contacting the owner of the group directly? There is an email for that on the homepage of the group. I don't know if there is a process for taking over a group where the owner have abandoned it.

Personally i lost the flame for that radio. The manufacturer support is non-existent and I tried contacting Venus Info Tech to try to get the manufacturer to open source the firmware, but obviously it led nowhere. There appear to be too little of a hacker community around it to start working on a new firmware from scratch too.

**Comment by musiclandUSA** [comment]
my biggest annoyance with it right now is the firmware ignores the imp/metric settings in all the menus, and mine arrived with much newer firmware and APRS software than is currently listed so evidently they're unaware of this bug

**Comment by marrold** [comment]
I've just seen this. The Github is largely dead as it was intended the manufacturer read the issues and resolve them.

As I'm not the manufacturer, there's not much I can do about it unfortunatly.

As for the groups.io mailing list, it's still active and I still approve new members and posts. If one got missed, apologies!
